apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
  - name: alma-linux
    image: almalinux:9
    command: ["sleep", "1000"]
    volumeMounts:
    - mountPath: /mnt/log/nginx
      name: nginx-logs
      readOnly: true
  volumes:
  - name: nginx-logs
    emptyDir:
      sizeLimit: 100Mi