apiVersion: v1
kind: Deployment
metadata:
  name: debug-machine
  namespace: roboshop   # This container should be in the same namespace for debugging purpose
spec:
  containers:
    - name: debug-machine
      image: srikanthsuthari/debug:v1