apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-machine
  namespace: roboshop   # This container should be in the same namespace for debugging purpose
  labels:
    name: debug-machine
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: debug-machine
      env: test
  template:
    metadata:
      name: debug-machine
      labels:
        name: debug-machine
        env: test
    spec:
      containers:
        - name: debug-machine
          image: srikanthsuthari/debug:v1