apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
data:
  
---
apiVersion: apps/v1
kind: deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
    tier: frontend
