apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: rabbitmq
      tier: backend
  template:
    metadata:
      name: rabbitmq
      labels:
        project: roboshop
        component: rabbitmq
        tier: backend
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:7
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 5372
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5372
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Service for rabbitmq
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: rabbitmq
    tier: backend
  ports:
  - protocol: TCP
    port: 5372
    targetPort: 5372