apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    name: mongodb
    env: db
spec:
  containers:
    - name: mongodb
      image: srikanthsuthari/mongodb:v1
      ports:
        - containerPort: 27017
      livenessProbe:
        httpGet:
          path: /health
          port: 27017
        initialDelaySeconds: 15
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /health
          port: 27017
        initialDelaySeconds: 5
        failureThreshold: 3
---
# Service of mongodb
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop     # if our pod in a seperate namespace then the service should also be in the same namespace
spec:
  type: ClusterIP
  selector:
    name: mongodb
    env: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
