apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    name: catalogue
    env: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: catalogue
      env: backend
  template:
    metadata:
      name: catalogue
      labels:
        name: catalogue
        env: backend
    spec:
      containers:
        - name: catalogue
          image: srikanthsuthari/catalogue:v1
          ports:
          - name: liveness-port
            containerPort: 8080
          imagePullPolicy: Always
      readinessProbe:
        httpGet:
          path: /health
          port: liveness-port     # another kind of usage for port
        initialDelaySeconds: 10
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /health
          port: liveness-port
        initialDelaySeconds: 20
        periodSeconds: 10
---
# Service for catalogue
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    name: catalogue
    env: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080